# Generated by Django 5.0.2 on 2024-04-08 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0039_facultyenrollmentdb_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseenrollmentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('ContactNo', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('GuardianName', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='images/')),
                ('Plustwo', models.FileField(upload_to='documents/')),
                ('SSLC', models.FileField(upload_to='documents/')),
                ('Plustwomark', models.CharField(max_length=20)),
                ('SSLCMark', models.CharField(max_length=20)),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.coursedb')),
            ],
        ),
    ]
