# Generated by Django 5.0.2 on 2024-04-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0041_multiplechoicequestion_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingdb',
            old_name='StudentId',
            new_name='Email',
        ),
    ]
