# Generated by Django 5.0.2 on 2024-04-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0042_rename_studentid_trainingdb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('StudentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.courseenrollmentdb')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.coursedb')),
            ],
        ),
    ]
