# Generated by Django 5.0.2 on 2024-04-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0043_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='StudentName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.studentdb'),
        ),
    ]
