# Generated by Django 5.0.2 on 2024-04-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0046_alter_payment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrollmentdb',
            old_name='CourseId',
            new_name='CourseName',
        ),
    ]
