# Generated by Django 5.0.2 on 2024-04-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0047_rename_courseid_courseenrollmentdb_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrollmentdb',
            old_name='CourseName',
            new_name='CourseId',
        ),
    ]
