# Generated by Django 5.0.2 on 2024-04-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0048_rename_coursename_courseenrollmentdb_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
