# Generated by Django 5.0.2 on 2024-04-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0049_payment_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedb',
            name='AdmissionFee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coursedb',
            name='Cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coursedb',
            name='Duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
