# Generated by Django 5.0.2 on 2024-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0050_coursedb_admissionfee_coursedb_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('shared', 'Shared')], max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('room_rent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
