# Generated by Django 5.0.2 on 2024-04-15 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0054_busbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminUI.studentdb'),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
