# Generated by Django 5.0.2 on 2024-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0058_alter_busbooking_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('ContactNo', models.CharField(max_length=20)),
                ('CourseName', models.CharField(max_length=20)),
            ],
        ),
    ]
