# Generated by Django 5.0.2 on 2024-04-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0061_alter_payment_amount_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='bus_timing',
        ),
    ]
