# Generated by Django 5.0.2 on 2024-05-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0062_remove_busbooking_bus_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedb',
            name='Syllabus',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
