# Generated by Django 5.0.2 on 2024-05-20 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0063_coursedb_syllabus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'verbose_name': 'Multiple Choice Question', 'verbose_name_plural': 'Multiple Choice Questions'},
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUI.coursedb', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Question Text'),
        ),
    ]
