# Generated by Django 5.0.2 on 2024-05-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0064_alter_multiplechoicequestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created At'),
        ),
    ]
