# Generated by Django 5.0.2 on 2024-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0067_alter_multiplechoicequestion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Created At'),
        ),
    ]
