# Generated by Django 5.0.2 on 2024-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0071_interviewdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdb',
            name='StudentName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
