# Generated by Django 5.0.2 on 2024-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0072_interviewdb_studentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdb',
            name='CourseName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admissiondb',
            name='ContactNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admissiondb',
            name='CourseName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admissiondb',
            name='DateOfBirth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admissiondb',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admissiondb',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admissiondb',
            name='StudentName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
