# Generated by Django 5.0.2 on 2024-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0073_interviewdb_coursename_alter_admissiondb_contactno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelroom',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hostelroom',
            unique_together={('room_number', 'gender')},
        ),
        migrations.AddIndex(
            model_name='hostelroom',
            index=models.Index(fields=['room_number', 'gender'], name='AdminUI_hos_room_nu_8c92e7_idx'),
        ),
    ]
