# Generated by Django 5.0.2 on 2024-05-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0075_alter_hostelroom_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
