# Generated by Django 5.0.2 on 2024-05-30 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0076_alter_studentdb_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='ContactNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='CourseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminUI.coursedb'),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='District',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='GuardianName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='Plustwo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='Plustwomark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='Religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='SSLC',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='SSLCMark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollmentdb',
            name='StudentName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
