# Generated by Django 5.0.2 on 2024-06-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0077_alter_courseenrollmentdb_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdb',
            name='InterviewStatus',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=10),
        ),
    ]
