# Generated by Django 5.0.2 on 2024-06-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0078_alter_interviewdb_interviewstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelroom',
            name='occupancy',
            field=models.PositiveIntegerField(default=0, help_text='Current number of occupants'),
        ),
    ]
