# Generated by Django 5.0.2 on 2024-06-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0079_hostelroom_occupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelroom',
            name='occupancy',
            field=models.PositiveIntegerField(blank=True, help_text='Current number of occupants', null=True),
        ),
    ]
