# Generated by Django 5.0.2 on 2024-06-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0080_alter_hostelroom_occupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='bus_fair',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='occupancy',
            field=models.PositiveIntegerField(blank=True, help_text='Available number of occupancy', null=True),
        ),
    ]
