# Generated by Django 5.0.2 on 2024-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0081_alter_busbooking_bus_fair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedb',
            name='Eligibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
